# source 'https://github.com/CocoaPods/Old-Specs.git'

# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'proyectoRiego2017' do

pod 'AFNetworking', '~>3.0'
pod 'CCTextFieldEffects'
pod 'Masonry'

end

target 'proyectoRiego2017Tests' do

end

target 'proyectoRiego2017UITests' do

end

