# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicaSubtipo',
            fields=[
                ('OIDCaracteristicaSubtipo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('atributo', models.CharField(max_length=20)),
                ('comentario', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ComponenteSensor',
            fields=[
                ('OIDComponenteSensor', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numeroComponente', models.IntegerField()),
                ('habilitado', models.BooleanField()),
                ('fechaAltaComponenteSensor', models.DateField()),
                ('fechaBajaComponenteSensor', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ComponenteSensorSector',
            fields=[
                ('OIDComponenteSensorSector', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idComponenteSensores', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionEventoPersonalizado',
            fields=[
                ('OIDConfiguracionEventoPersonalizado', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idConfiguracion', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('notificacionActivada', models.BooleanField()),
                ('fechaAltaConfiguracionEventoPersonalizado', models.DateField()),
                ('fechaBajaConfiguracionEventoPersonalizado', models.DateField()),
                ('fechaHoraCreacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionRiego',
            fields=[
                ('OIDConfiguracionRiego', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('duracionMaxima', models.FloatField()),
                ('fechaCreacion', models.DateField()),
                ('fechaFinalizacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Contrasenia',
            fields=[
                ('OIDContrasenia', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fechaAltaContrasenia', models.DateField()),
                ('fechaBajaContrasenia', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CriterioRiego',
            fields=[
                ('OIDCriterioRiego', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fechaCreacionCriterio', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('OIDCultivo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=20)),
                ('fechaPlantacion', models.DateField()),
                ('fechaEliminacion', models.DateField()),
                ('habilitado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='EjecucionRiego',
            fields=[
                ('OIDEjecucionRiego', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidadAguaUtilizada', models.FloatField()),
                ('detalle', models.CharField(max_length=100)),
                ('duracionActual', models.FloatField()),
                ('fechaHoraFinalizacion', models.DateField()),
                ('fechaHoraFinalProgramada', models.DateField()),
                ('fechaHoraInicio', models.DateField()),
                ('fechaHoraInicioProgramada', models.DateField()),
                ('configuracion_riego', models.ForeignKey(db_column=b'OIDConfiguracionRiego', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.ConfiguracionRiego')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoComponenteSensorSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEstadoSensorSector', models.CharField(max_length=20)),
                ('descripcionEstadoSensorSector', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoConfiguracionRiego',
            fields=[
                ('OIDEstadoConfiguracionRiego', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombreEstadoConfiguracionRiego', models.CharField(max_length=20, unique=True)),
                ('descripcionEstadoConfiguracionRiego', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoEjecucionRiego',
            fields=[
                ('OIDEstadoEjecucionRiego', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombreEstadoEjecucionRiego', models.CharField(max_length=20, unique=True)),
                ('descripcionEstadoEjecucionRiego', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoFinca',
            fields=[
                ('OIDFinca', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcionEstadoFinca', models.CharField(max_length=100)),
                ('nombreEstadoFinca', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoMecanismoRiegoFinca',
            fields=[
                ('OIDEstadoMecanismoRiegoFinca', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombreEstadoMecanismoRiegoFincaSector', models.CharField(max_length=20)),
                ('descripcionEstadoMecanismoRiegoFincaSector', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoMecanismoRiegoFincaSector',
            fields=[
                ('OIDEstadoMecanismoRiegoFincaSector', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcionEstadoMecanismoRiegoFincaSector', models.CharField(max_length=100)),
                ('nombreEstadoMecanismoRiegoFincaSector', models.CharField(max_length=29)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoSector',
            fields=[
                ('OIDEstadoSector', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcionEstadoSector', models.CharField(max_length=100)),
                ('nombreEstadoSector', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoUsuario',
            fields=[
                ('OIDEstadoUsuario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcionEstadoUsuario', models.CharField(max_length=100)),
                ('nombreEstadoUsuario', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EventoPersonalizado',
            fields=[
                ('OIDEventoPersonalizado', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nroEvento', models.IntegerField(unique=True)),
                ('fechaHora', models.DateField()),
                ('configuracion_evento_personalizado', models.ForeignKey(db_column=b'OIDConfiguracionEventoPersonalizado', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.ConfiguracionEventoPersonalizado')),
            ],
        ),
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('OIDFinca', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direccionLegal', models.CharField(max_length=50)),
                ('idFinca', models.IntegerField()),
                ('logoFinca', models.ImageField(upload_to=b'')),
                ('nombre', models.CharField(max_length=50)),
                ('tamanio', models.FloatField()),
                ('ubicacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoComponenteSensorSector',
            fields=[
                ('OIDHistoricoComponenteSensorSector', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fechaAltaComponenteSensorSector', models.DateField()),
                ('fechaBajaComponenteSensorSecto', models.DateField()),
                ('componenteSensorSector', models.ForeignKey(db_column=b'OIDComponenteSensorSector', on_delete=django.db.models.deletion.CASCADE, related_name='historicoComponenteSensorSector', to='riegoInteligente.ComponenteSensorSector')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoEstadoConfiguracionRiego',
            fields=[
                ('OIDHistoricoEstadoConfiguracionRiego', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fechaFinEstadoConfiguracionRiego', models.DateField()),
                ('fechaInicioEstadoConfiguracionRiego', models.DateField()),
                ('configuracion_riego', models.ForeignKey(db_column=b'OIDConfiguracionRiego', on_delete=django.db.models.deletion.CASCADE, related_name='historicoEstadoConfiguracionRiegoList', to='riegoInteligente.ConfiguracionRiego')),
                ('estado_configuracion_riego', models.ForeignKey(db_column=b'OIDEstadoConfiguracionRiego', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.EstadoConfiguracionRiego')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoEstadoFinca',
            fields=[
                ('OIDHistoricoEstadoFinca', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fechaFinEstadoFinca', models.DateField()),
                ('fechaInicioEstadoFinca', models.DateField()),
                ('estado_finca', models.ForeignKey(db_column=b'OIDEstadoFinca', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.EstadoFinca')),
                ('finca', models.ForeignKey(db_column=b'OIDFinca', on_delete=django.db.models.deletion.CASCADE, related_name='historicoEstadoFinca', to='riegoInteligente.Finca')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoEstadoSector',
            fields=[
                ('OIDHistoricoEstadoSector', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fechaFinEstadoSector', models.DateField()),
                ('fechaInicioEstadoSector', models.DateField()),
                ('estado_sector', models.ForeignKey(db_column=b'OIDEstadoSector', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.EstadoSector')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoEstadoUsuario',
            fields=[
                ('OIDHistoricoEstadoUsuario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fechaFinEstadoUsuario', models.DateField()),
                ('fechaInicioEstadoUsuario', models.DateField()),
                ('estadoUsuario', models.ForeignKey(db_column=b'OIDEstadoUsuario', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.EstadoUsuario')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoMecanismoRiegoFinca',
            fields=[
                ('OIDHistoricoMecanismoRiegoFinca', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado_mecanismo_riego_finca', models.ForeignKey(db_column=b'OIDEstadoMecanismoRiegoFinca', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.EstadoMecanismoRiegoFinca')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoMecanismoRiegoFincaSector',
            fields=[
                ('OIDHistoricoMecanismoRiegoFincaSector', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fechaFinEstadoMecanismoRiegoFincaSector', models.DateField()),
                ('fechaInicioEstadoMecanismoRiegoFincaSector', models.DateField()),
                ('estado_mecanismo_riego_finca_sector', models.ForeignKey(db_column=b'OIDEstadoMecanismoRiegoFincaSector', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.EstadoMecanismoRiegoFincaSector')),
            ],
        ),
        migrations.CreateModel(
            name='MecanismoRiegoFinca',
            fields=[
                ('OIDMecanismoRiegoFinca', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direccionIP', models.CharField(max_length=20)),
                ('fechaInstalacion', models.DateField()),
                ('idFincaMecanismoRiego', models.IntegerField()),
                ('finca', models.ForeignKey(db_column=b'OIDFinca', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.Finca')),
            ],
        ),
        migrations.CreateModel(
            name='MecanismoRiegoFincaSector',
            fields=[
                ('OIDMecanismoRiegoFincaSector', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('caudal', models.FloatField()),
                ('presion', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicionCabecera',
            fields=[
                ('OIDMedicionCabecera', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fechaYHora', models.DateField()),
                ('nroMedicion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicionDetalle',
            fields=[
                ('OIDMedicionDetalle', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nroRenglon', models.IntegerField()),
                ('valor', models.FloatField()),
                ('medicionCabecera', models.ForeignKey(db_column=b'OIDMedicionCabecera', on_delete=django.db.models.deletion.CASCADE, related_name='medicionDetalle', to='riegoInteligente.MedicionCabecera')),
            ],
        ),
        migrations.CreateModel(
            name='MedicionEvento',
            fields=[
                ('OIDMedicionEvento', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valorMaximo', models.FloatField()),
                ('valorMinimo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicionInformacionClimaticaCabecera',
            fields=[
                ('OIDMedicionInformacionClimaticaCabecera', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nroMedicion', models.IntegerField(unique=True)),
                ('fechaHora', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicionInformacionClimaticaDetalle',
            fields=[
                ('OIDMedicionInformacionClimaticaDetalle', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nroRenglon', models.IntegerField()),
                ('valor', models.FloatField()),
                ('medicion_informacion_climatica_cabecera', models.ForeignKey(db_column=b'OIDMedicionInformacionClimaticaCabecera', on_delete=django.db.models.deletion.CASCADE, related_name='medicionInformacionClimaticaDetalle', to='riegoInteligente.MedicionInformacionClimaticaCabecera')),
            ],
        ),
        migrations.CreateModel(
            name='MetodoProveedorInformacionClimatica',
            fields=[
                ('OIDMetodoProveedorInformacionClimatica', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nombreMetodo', models.CharField(max_length=40)),
                ('tipoMetodo', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('OIDParametro', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('metodo_proveedor_informacion_climatica', models.ForeignKey(db_column=b'OIDMetodoProveedorInformacionClimatica', on_delete=django.db.models.deletion.CASCADE, related_name='parametro_list', to='riegoInteligente.MetodoProveedorInformacionClimatica')),
            ],
        ),
        migrations.CreateModel(
            name='ProveedorInformacionClimatica',
            fields=[
                ('OIDProveedorInformacionClimatica', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nombreProveedor', models.CharField(max_length=20, unique=True)),
                ('habilitado', models.BooleanField()),
                ('urlAPI', models.CharField(max_length=100)),
                ('frecuenciaMaxPosible', models.IntegerField()),
                ('fechaAltaProveedorInfoClimatica', models.DateField()),
                ('fechaBajaProveedorInfoClimatica', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProveedorInformacionClimaticaFinca',
            fields=[
                ('OIDProveedorInformacionClimaticaFinca', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fechaAltaProveedorInfoClimaticaFinca', models.DateField()),
                ('fechaBajaProveedorInfoClimaticaFinca', models.DateField()),
                ('frecuencia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('OIDRol', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombreRol', models.CharField(max_length=10)),
                ('fechaAltaRol', models.DateField()),
                ('fechaBajaRol', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('OIDSector', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numeroSector', models.IntegerField()),
                ('nombreSector', models.CharField(max_length=20)),
                ('descripcionSector', models.CharField(max_length=100)),
                ('superficie', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('OIDSensor', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idSensor', models.IntegerField()),
                ('fechaAltaSensor', models.DateField()),
                ('fechaBajaSensor', models.DateField()),
                ('habilitado', models.BooleanField()),
                ('modelo', models.CharField(max_length=20)),
                ('componente_sensor', models.ForeignKey(db_column=b'OIDComponenteSensor', on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='riegoInteligente.ComponenteSensor')),
                ('finca', models.ForeignKey(db_column=b'OIDFinca', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.Finca')),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('OIDSesion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fechaYHoraFin', models.DateField()),
                ('fechaYHoraInicio', models.DateField()),
                ('idSesion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SubtipoCultivo',
            fields=[
                ('OIDSubtipoCultivo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idSubtipo', models.IntegerField(unique=True)),
                ('nombreSubtipo', models.CharField(max_length=20)),
                ('habilitado', models.BooleanField()),
                ('descripcion', models.CharField(max_length=100)),
                ('fechaAltaSubtipoCultivo', models.DateField()),
                ('fechaBajaSubtipoCultivo', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoConfiguracionRiego',
            fields=[
                ('OIDTipoConfiguracionRiego', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idTipoConfiguracion', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCultivo',
            fields=[
                ('OIDTipoCultivo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idTipo', models.IntegerField(unique=True)),
                ('nombreTipoCultivo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('habilitado', models.BooleanField()),
                ('fechaAltaTipoCultivo', models.DateField()),
                ('fechaBajaTipoCultivo', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoMedicion',
            fields=[
                ('OIDTipoMedicion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idTipoMedicion', models.IntegerField()),
                ('nombreTipoMedicion', models.CharField(max_length=20)),
                ('unidadMedicion', models.CharField(max_length=20)),
                ('habilitado', models.BooleanField()),
                ('fechaAltaTipoMedicion', models.DateField()),
                ('fechaBajaTipoMedicion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoMedicionClimatica',
            fields=[
                ('OIDTipoMedicionClimatica', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('idTipoMedicionClimatica', models.IntegerField(unique=True)),
                ('nombreTipoMedicionClimatica', models.IntegerField(unique=True)),
                ('tipoDato', models.CharField(max_length=10)),
                ('fechaAltaTipoMedicionClimatica', models.DateField()),
                ('fechaBajaTipoMedicionClimatica', models.DateField()),
                ('habilitada', models.BooleanField()),
                ('metodo_proveedor_informacion_climatica', models.ForeignKey(db_column=b'OIDMetodoProveedorInformacionClimatica', on_delete=django.db.models.deletion.CASCADE, related_name='tipoMedicionClimatica', to='riegoInteligente.MetodoProveedorInformacionClimatica')),
            ],
        ),
        migrations.CreateModel(
            name='TipoSesion',
            fields=[
                ('OIDTipoSesion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idTipo', models.IntegerField()),
                ('nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('OIDUsuario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('cuit', models.CharField(max_length=15)),
                ('dni', models.IntegerField()),
                ('domicilio', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('fechaNacimiento', models.DateField()),
                ('imagenUsuario', models.ImageField(upload_to=b'')),
                ('OIDEstadoUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.EstadoUsuario')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioFinca',
            fields=[
                ('OIDUsuarioFinca', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fechaAltaUsuarioFinca', models.DateField()),
                ('fechaBajaUsuarioFinca', models.DateField()),
                ('finca', models.ForeignKey(db_column=b'OIDFinca', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.Finca')),
                ('usuario', models.ForeignKey(db_column=b'OIDUsuario', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='CriterioRiegoPorHora',
            fields=[
                ('criterioriego_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='riegoInteligente.CriterioRiego')),
                ('hora', models.DateField()),
                ('numeroDia', models.IntegerField()),
            ],
            bases=('riegoInteligente.criterioriego',),
        ),
        migrations.CreateModel(
            name='CriterioRiegoPorMedicion',
            fields=[
                ('criterioriego_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='riegoInteligente.CriterioRiego')),
                ('valor', models.FloatField()),
            ],
            bases=('riegoInteligente.criterioriego',),
        ),
        migrations.CreateModel(
            name='CriterioRiegoVolumenAgua',
            fields=[
                ('criterioriego_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='riegoInteligente.CriterioRiego')),
                ('volumen', models.FloatField()),
            ],
            bases=('riegoInteligente.criterioriego',),
        ),
        migrations.CreateModel(
            name='MedicionEstadoExterno',
            fields=[
                ('medicionevento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='riegoInteligente.MedicionEvento')),
                ('tipo_medicion_climatica', models.ForeignKey(db_column=b'OIDTipoMedicionClimatica', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.TipoMedicionClimatica')),
            ],
            bases=('riegoInteligente.medicionevento',),
        ),
        migrations.CreateModel(
            name='MedicionFuenteInterna',
            fields=[
                ('medicionevento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='riegoInteligente.MedicionEvento')),
                ('tipoMedicion', models.ForeignKey(db_column=b'OIDTipoMedicion', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.TipoMedicion')),
            ],
            bases=('riegoInteligente.medicionevento',),
        ),
        migrations.AddField(
            model_name='subtipocultivo',
            name='tipo_cultivo',
            field=models.ForeignKey(db_column=b'OIDTipoCultivo', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.TipoCultivo'),
        ),
        migrations.AddField(
            model_name='sesion',
            name='tipoSesion',
            field=models.ForeignKey(db_column=b'OIDTipoSesion', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.TipoSesion'),
        ),
        migrations.AddField(
            model_name='sesion',
            name='usuario',
            field=models.ForeignKey(db_column=b'OIDUsuario', on_delete=django.db.models.deletion.CASCADE, related_name='sesion', to='riegoInteligente.Usuario'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensorTipoInterna',
            field=models.ForeignKey(db_column=b'OIDTipoMedicion', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.TipoMedicion'),
        ),
        migrations.AddField(
            model_name='proveedorinformacionclimatica',
            name='tipo_medicion_climatica',
            field=models.ManyToManyField(to='riegoInteligente.TipoMedicionClimatica'),
        ),
        migrations.AddField(
            model_name='metodoproveedorinformacionclimatica',
            name='proveedor_informacion_climatica',
            field=models.ForeignKey(db_column=b'OIDProveedorInformacionClimatica', on_delete=django.db.models.deletion.CASCADE, related_name='metodoProveedorInformacionClimaticaList', to='riegoInteligente.ProveedorInformacionClimatica'),
        ),
        migrations.AddField(
            model_name='medicioninformacionclimaticadetalle',
            name='tipo_medicion_climatica',
            field=models.ForeignKey(db_column=b'OIDTipoMedicionClimatica', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.TipoMedicionClimatica'),
        ),
        migrations.AddField(
            model_name='medicioninformacionclimaticacabecera',
            name='proveedor_informacion_climatica_externa',
            field=models.ForeignKey(db_column=b'OIDProveedorInformacionClimaticaFinca', on_delete=django.db.models.deletion.CASCADE, related_name='medicionInformacionClimaticaCabeceraList', to='riegoInteligente.ProveedorInformacionClimaticaFinca'),
        ),
        migrations.AddField(
            model_name='medicionevento',
            name='configuracionEventoPersonalizado',
            field=models.ForeignKey(db_column=b'OIDConfiguracionEventoPersonalizado', on_delete=django.db.models.deletion.CASCADE, related_name='medicionEventoList', to='riegoInteligente.EventoPersonalizado'),
        ),
        migrations.AddField(
            model_name='historicomecanismoriegofincasector',
            name='mecanismo_riego_finca_sector',
            field=models.ForeignKey(db_column=b'OIDMecanismoRiegoFincaSector', on_delete=django.db.models.deletion.CASCADE, related_name='historicoMecanismoRiegoFincaSector', to='riegoInteligente.MecanismoRiegoFincaSector'),
        ),
        migrations.AddField(
            model_name='historicomecanismoriegofinca',
            name='mecanismo_riego_finca',
            field=models.ForeignKey(db_column=b'OIDMecanismoRiegoFinca', on_delete=django.db.models.deletion.CASCADE, related_name='historicoMecanismoRiegoFinca', to='riegoInteligente.MecanismoRiegoFinca'),
        ),
        migrations.AddField(
            model_name='historicoestadousuario',
            name='usuario',
            field=models.ForeignKey(db_column=b'OIDUsuario', on_delete=django.db.models.deletion.CASCADE, related_name='historicoEstadoUsuario', to='riegoInteligente.Usuario'),
        ),
        migrations.AddField(
            model_name='historicoestadosector',
            name='sector',
            field=models.ForeignKey(db_column=b'OIDSector', on_delete=django.db.models.deletion.CASCADE, related_name='historicoEstadoSector', to='riegoInteligente.Sector'),
        ),
        migrations.AddField(
            model_name='finca',
            name='proveedor_informacion_climatica_finca',
            field=models.ForeignKey(db_column=b'OIDProveedorInformacionClimaticaFinca', on_delete=django.db.models.deletion.CASCADE, related_name='finca', to='riegoInteligente.ProveedorInformacionClimaticaFinca'),
        ),
        migrations.AddField(
            model_name='ejecucionriego',
            name='estado_ejecucion_riego',
            field=models.ForeignKey(db_column=b'OIDEstadoEjecucionRiego', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.EstadoEjecucionRiego'),
        ),
        migrations.AddField(
            model_name='ejecucionriego',
            name='mecanismo_riego_finca_sector',
            field=models.ForeignKey(db_column=b'OIDMecanismoRiegoFincaSector', on_delete=django.db.models.deletion.CASCADE, related_name='ejecucionRiegoList', to='riegoInteligente.MecanismoRiegoFincaSector'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='sector',
            field=models.ForeignKey(db_column=b'OIDSector', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.Sector'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='subtipo_cultivo',
            field=models.ForeignKey(db_column=b'OIDSubtipoCultivo', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.SubtipoCultivo'),
        ),
        migrations.AddField(
            model_name='criterioriego',
            name='configuracionRiegoFinal',
            field=models.ForeignKey(db_column=b'OIDConfiguracionRiegoFinal', on_delete=django.db.models.deletion.CASCADE, related_name='criterioRiegoFinal', to='riegoInteligente.ConfiguracionRiego'),
        ),
        migrations.AddField(
            model_name='criterioriego',
            name='configuracionRiegoInicial',
            field=models.OneToOneField(db_column=b'OIDconfiguracionRiegoInicial', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.ConfiguracionRiego'),
        ),
        migrations.AddField(
            model_name='contrasenia',
            name='OIDUsuario',
            field=models.ForeignKey(db_column=b'OIDUsuario', on_delete=django.db.models.deletion.CASCADE, related_name='contrasenia', to='riegoInteligente.Usuario'),
        ),
        migrations.AddField(
            model_name='configuracionriego',
            name='mecanismoRiegoFincaSector',
            field=models.ForeignKey(db_column=b'OIDMecanismoRiegoFincaSector', null=True, on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.MecanismoRiegoFincaSector'),
        ),
        migrations.AddField(
            model_name='configuracionriego',
            name='tipoConfiguracionRiego',
            field=models.ForeignKey(db_column=b'OIDTipoConfiguracionRiego', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.TipoConfiguracionRiego'),
        ),
        migrations.AddField(
            model_name='configuracioneventopersonalizado',
            name='usuario_finca',
            field=models.ForeignKey(db_column=b'OIDUsuarioFinca', on_delete=django.db.models.deletion.CASCADE, related_name='usuarioFinca', to='riegoInteligente.UsuarioFinca'),
        ),
        migrations.AddField(
            model_name='componentesensorsector',
            name='componente_sensor',
            field=models.ForeignKey(db_column=b'OIDSector', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.Sector'),
        ),
        migrations.AddField(
            model_name='caracteristicasubtipo',
            name='subtipo_cultivo',
            field=models.ForeignKey(db_column=b'OIDSubtipoCultivo', on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicaSubtipoList', to='riegoInteligente.SubtipoCultivo'),
        ),
    ]
