# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 19:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionSensorComponente',
            fields=[
                ('OIDAsignacionSensorComponente', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fechaAsignacion', models.DateTimeField()),
                ('fechaBaja', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaracteristicaSubtipo',
            fields=[
                ('OIDCaracteristicaSubtipo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('atributo', models.CharField(max_length=20)),
                ('comentario', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ComponenteSensor',
            fields=[
                ('OIDComponenteSensor', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idComponenteSensor', models.IntegerField(default=1, editable=False, unique=True)),
                ('modelo', models.CharField(max_length=100, null=True)),
                ('descripcion', models.CharField(max_length=200, null=True)),
                ('cantidadMaximaSensores', models.IntegerField(null=True)),
                ('cantidadSensoresAsignados', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ComponenteSensorSector',
            fields=[
                ('OIDComponenteSensorSector', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idComponenteSensorSector', models.IntegerField(default=1, editable=False, unique=True)),
                ('habilitado', models.BooleanField()),
                ('componente_sensor', models.ForeignKey(db_column=b'OIDComponenteSensor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='componenteSensorSectorList', to='riegoInteligente.ComponenteSensor')),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionEventoPersonalizado',
            fields=[
                ('OIDConfiguracionEventoPersonalizado', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idConfiguracion', models.IntegerField(default=1, editable=False, unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('notificacionActivada', models.BooleanField()),
                ('fechaAltaConfiguracionEventoPersonalizado', models.DateTimeField()),
                ('fechaBajaConfiguracionEventoPersonalizado', models.DateTimeField(null=True)),
                ('fechaHoraCreacion', models.DateTimeField()),
                ('activado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionRiego',
            fields=[
                ('OIDConfiguracionRiego', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_configuracion_riego', models.IntegerField(default=1, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('duracionMaxima', models.FloatField()),
                ('fechaCreacion', models.DateTimeField()),
                ('fechaFinalizacion', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConjuntoPermisos',
            fields=[
                ('OIDConjuntoPermisos', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('puedeAsignarComponenteSensor', models.BooleanField()),
                ('puedeAsignarCultivo', models.BooleanField()),
                ('puedeAsignarMecRiegoAFinca', models.BooleanField()),
                ('puedeAsignarMecRiegoASector', models.BooleanField()),
                ('puedeConfigurarObtencionInfoExterna', models.BooleanField()),
                ('puedeCrearComponenteSensor', models.BooleanField()),
                ('puedeCrearConfiguracionRiego', models.BooleanField()),
                ('puedeCrearSector', models.BooleanField()),
                ('puedeGenerarInformeCruzadoRiegoMedicion', models.BooleanField()),
                ('puedeGenerarInformeEstadoActualSectores', models.BooleanField()),
                ('puedeGenerarInformeEstadoHistoricoSectoresFinca', models.BooleanField()),
                ('puedeGenerarInformeEventoPersonalizado', models.BooleanField()),
                ('puedeGenerarInformeHeladasHistorico', models.BooleanField()),
                ('puedeGenerarInformeRiegoEnEjecucion', models.BooleanField()),
                ('puedeGenerarInformeRiegoPorSectoresHistorico', models.BooleanField()),
                ('puedeGestionarComponenteSensor', models.BooleanField()),
                ('puedeGestionarCultivoSector', models.BooleanField()),
                ('puedeGestionarEventoPersonalizado', models.BooleanField()),
                ('puedeGestionarFinca', models.BooleanField()),
                ('puedeGestionarSector', models.BooleanField()),
                ('puedeGestionarSensores', models.BooleanField()),
                ('puedeGestionarUsuariosFinca', models.BooleanField()),
                ('puedeIniciarODetenerRiegoManualmente', models.BooleanField()),
                ('puedeModificarConfiguracionRiego', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CriterioRiego',
            fields=[
                ('OIDCriterioRiego', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_criterio_riego', models.IntegerField(default=1, editable=False, unique=True)),
                ('fecha_creacion_criterio', models.DateTimeField()),
                ('fecha_eliminacion_criterio', models.DateTimeField(null=True)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('descripcion', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('OIDCultivo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idCultivo', models.IntegerField(default=1, editable=False, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=20)),
                ('fechaPlantacion', models.DateTimeField()),
                ('fechaEliminacion', models.DateTimeField(null=True)),
                ('habilitado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DatosUsuario',
            fields=[
                ('OIDDatosUsuario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cuit', models.CharField(max_length=15, null=True)),
                ('dni', models.IntegerField(null=True)),
                ('domicilio', models.CharField(max_length=50, null=True)),
                ('fechaNacimiento', models.DateTimeField(null=True)),
                ('imagenUsuario', models.ImageField(null=True, upload_to=b'')),
                ('reset_password', models.BooleanField(default=False)),
                ('codigoVerificacion', models.CharField(max_length=10, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EjecucionRiego',
            fields=[
                ('oid_ejecucion_riego', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detalle', models.CharField(max_length=100)),
                ('duracion_parcial', models.FloatField(default=0)),
                ('fecha_hora_ultima_pausa', models.DateTimeField(null=True)),
                ('fecha_hora_ultimo_reinicio', models.DateTimeField(null=True)),
                ('fecha_hora_finalizacion', models.DateTimeField(null=True)),
                ('fecha_hora_final_programada', models.DateTimeField(null=True)),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_inicio_programada', models.DateTimeField(null=True)),
                ('configuracion_riego', models.ForeignKey(db_column=b'OIDConfiguracionRiego', null=True, on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.ConfiguracionRiego')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoComponenteSensor',
            fields=[
                ('OIDEstadoComponenteSensor', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombreEstado', models.CharField(max_length=20)),
                ('descripcionEstado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoComponenteSensorSector',
            fields=[
                ('OIDEstadoComponenteSensorSector', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombreEstadoComponenteSensorSector', models.CharField(max_length=20)),
                ('descripcionEstadoComponenteSensorSector', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoConfiguracionRiego',
            fields=[
                ('OIDEstadoConfiguracionRiego', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombreEstadoConfiguracionRiego', models.CharField(max_length=20, unique=True)),
                ('descripcionEstadoConfiguracionRiego', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoEjecucionRiego',
            fields=[
                ('OIDEstadoEjecucionRiego', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombreEstadoEjecucionRiego', models.CharField(max_length=20, unique=True)),
                ('descripcionEstadoEjecucionRiego', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoFinca',
            fields=[
                ('OIDFinca', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcionEstadoFinca', models.CharField(max_length=100)),
                ('nombreEstadoFinca', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoMecanismoRiegoFinca',
            fields=[
                ('OIDEstadoMecanismoRiegoFinca', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombreEstadoMecanismoRiegoFinca', models.CharField(max_length=20)),
                ('descripcionEstadoMecanismoRiegoFinca', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoMecanismoRiegoFincaSector',
            fields=[
                ('OIDEstadoMecanismoRiegoFincaSector', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcionEstadoMecanismoRiegoFincaSector', models.CharField(max_length=100)),
                ('nombreEstadoMecanismoRiegoFincaSector', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoSector',
            fields=[
                ('OIDEstadoSector', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcionEstadoSector', models.CharField(max_length=100)),
                ('nombreEstadoSector', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoUsuario',
            fields=[
                ('OIDEstadoUsuario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcionEstadoUsuario', models.CharField(max_length=100)),
                ('nombreEstadoUsuario', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EventoPersonalizado',
            fields=[
                ('OIDEventoPersonalizado', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nroEvento', models.IntegerField(default=1, unique=True)),
                ('fechaHora', models.DateTimeField()),
                ('configuracion_evento_personalizado', models.ForeignKey(db_column=b'OIDConfiguracionEventoPersonalizado', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.ConfiguracionEventoPersonalizado')),
            ],
        ),
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('OIDFinca', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idFinca', models.IntegerField(default=1, editable=False, unique=True)),
                ('direccionLegal', models.CharField(max_length=50)),
                ('logoFinca', models.ImageField(null=True, upload_to=b'')),
                ('nombre', models.CharField(max_length=50)),
                ('tamanio', models.FloatField()),
                ('ubicacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoEstadoComponenteSensor',
            fields=[
                ('OIDHistoricoEstadoComponenteSensor', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fechaFinEstadoComponenteSensor', models.DateTimeField(null=True)),
                ('fechaInicioEstadoComponenteSensor', models.DateTimeField()),
                ('componenteSensor', models.ForeignKey(db_column=b'OIDComponenteSensor', on_delete=django.db.models.deletion.CASCADE, related_name='historico_estado_componente_sensor_list', to='riegoInteligente.ComponenteSensor')),
                ('estadoComponenteSensor', models.ForeignKey(db_column=b'OIDEstadoComponenteSensor', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.EstadoComponenteSensor')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoEstadoComponenteSensorSector',
            fields=[
                ('OIDHistoricoEstadoComponenteSensorSector', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fechaAltaComponenteSensorSector', models.DateTimeField()),
                ('fechaBajaComponenteSensorSector', models.DateTimeField(null=True)),
                ('componenteSensorSector', models.ForeignKey(db_column=b'OIDComponenteSensorSector', on_delete=django.db.models.deletion.CASCADE, related_name='historicoEstadoComponenteSensorSector', to='riegoInteligente.ComponenteSensorSector')),
                ('estadoComponenteSensorSector', models.ForeignKey(db_column=b'OIDEstadoComponenteSensorSector', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.EstadoComponenteSensorSector')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoEstadoConfiguracionRiego',
            fields=[
                ('OIDHistoricoEstadoConfiguracionRiego', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fechaFinEstadoConfiguracionRiego', models.DateTimeField(null=True)),
                ('fechaInicioEstadoConfiguracionRiego', models.DateTimeField()),
                ('configuracion_riego', models.ForeignKey(db_column=b'OIDConfiguracionRiego', on_delete=django.db.models.deletion.CASCADE, related_name='historicoEstadoConfiguracionRiegoList', to='riegoInteligente.ConfiguracionRiego')),
                ('estado_configuracion_riego', models.ForeignKey(db_column=b'OIDEstadoConfiguracionRiego', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.EstadoConfiguracionRiego')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoEstadoFinca',
            fields=[
                ('OIDHistoricoEstadoFinca', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fechaFinEstadoFinca', models.DateTimeField(null=True)),
                ('fechaInicioEstadoFinca', models.DateTimeField()),
                ('estadoFinca', models.ForeignKey(db_column=b'OIDEstadoFinca', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.EstadoFinca')),
                ('finca', models.ForeignKey(db_column=b'OIDFinca', on_delete=django.db.models.deletion.CASCADE, related_name='historicoEstadoFincaList', to='riegoInteligente.Finca')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoEstadoSector',
            fields=[
                ('OIDHistoricoEstadoSector', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fechaFinEstadoSector', models.DateTimeField(null=True)),
                ('fechaInicioEstadoSector', models.DateTimeField()),
                ('estado_sector', models.ForeignKey(db_column=b'OIDEstadoSector', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.EstadoSector')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoEstadoUsuario',
            fields=[
                ('OIDHistoricoEstadoUsuario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fechaFinEstadoUsuario', models.DateTimeField(null=True)),
                ('fechaInicioEstadoUsuario', models.DateTimeField()),
                ('estadoUsuario', models.ForeignKey(db_column=b'OIDEstadoUsuario', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.EstadoUsuario')),
                ('usuario', models.ForeignKey(db_column=b'OIDUsuario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historicoEstadoUsuarioList', to='riegoInteligente.DatosUsuario')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoMecanismoRiegoFinca',
            fields=[
                ('OIDHistoricoMecanismoRiegoFinca', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fechaInicioEstadoMecanismoRiegoFinca', models.DateTimeField(null=True)),
                ('fechaFinEstadoMecanismoRiegoFinca', models.DateTimeField(null=True)),
                ('estado_mecanismo_riego_finca', models.ForeignKey(db_column=b'OIDEstadoMecanismoRiegoFinca', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.EstadoMecanismoRiegoFinca')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoMecanismoRiegoFincaSector',
            fields=[
                ('OIDHistoricoMecanismoRiegoFincaSector', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fechaFinEstadoMecanismoRiegoFincaSector', models.DateTimeField(null=True)),
                ('fechaInicioEstadoMecanismoRiegoFincaSector', models.DateTimeField()),
                ('estado_mecanismo_riego_finca_sector', models.ForeignKey(db_column=b'OIDEstadoMecanismoRiegoFincaSector', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.EstadoMecanismoRiegoFincaSector')),
            ],
        ),
        migrations.CreateModel(
            name='MecanismoRiegoFinca',
            fields=[
                ('OIDMecanismoRiegoFinca', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direccionIP', models.CharField(max_length=20)),
                ('fechaInstalacion', models.DateTimeField()),
                ('idMecanismoRiegoFinca', models.IntegerField(default=1, editable=False, unique=True)),
                ('finca', models.ForeignKey(db_column=b'OIDFinca', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.Finca')),
            ],
        ),
        migrations.CreateModel(
            name='MecanismoRiegoFincaSector',
            fields=[
                ('OIDMecanismoRiegoFincaSector', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idMecanismoRiegoFincaSector', models.IntegerField(default=1, unique=True)),
                ('caudal', models.FloatField()),
                ('presion', models.FloatField()),
                ('mecanismoRiegoFinca', models.ForeignKey(db_column=b'OIDMecanismoRiegoFinca', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mecanismoRiegoSectorList', to='riegoInteligente.MecanismoRiegoFinca')),
            ],
        ),
        migrations.CreateModel(
            name='MedicionCabecera',
            fields=[
                ('OIDMedicionCabecera', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fechaYHora', models.DateTimeField()),
                ('nroMedicion', models.IntegerField(default=1, unique=True)),
                ('componenteSensorSector', models.ForeignKey(db_column=b'OIDComponenteSensorSector', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicionCabeceraList', to='riegoInteligente.ComponenteSensorSector')),
            ],
        ),
        migrations.CreateModel(
            name='MedicionDetalle',
            fields=[
                ('OIDMedicionDetalle', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nroRenglon', models.IntegerField()),
                ('valor', models.FloatField()),
                ('medicionCabecera', models.ForeignKey(db_column=b'OIDMedicionCabecera', on_delete=django.db.models.deletion.CASCADE, related_name='medicionDetalleList', to='riegoInteligente.MedicionCabecera')),
            ],
        ),
        migrations.CreateModel(
            name='MedicionEvento',
            fields=[
                ('OIDMedicionEvento', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valorMaximo', models.FloatField()),
                ('valorMinimo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicionInformacionClimaticaCabecera',
            fields=[
                ('OIDMedicionInformacionClimaticaCabecera', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nroMedicion', models.IntegerField(unique=True)),
                ('fechaHora', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicionInformacionClimaticaDetalle',
            fields=[
                ('OIDMedicionInformacionClimaticaDetalle', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nroRenglon', models.IntegerField()),
                ('valor', models.FloatField()),
                ('medicion_informacion_climatica_cabecera', models.ForeignKey(db_column=b'OIDMedicionInformacionClimaticaCabecera', on_delete=django.db.models.deletion.CASCADE, related_name='medicionInformacionClimaticaDetalle', to='riegoInteligente.MedicionInformacionClimaticaCabecera')),
            ],
        ),
        migrations.CreateModel(
            name='ProveedorInformacionClimatica',
            fields=[
                ('OIDProveedorInformacionClimatica', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombreProveedor', models.CharField(max_length=20, unique=True)),
                ('habilitado', models.BooleanField()),
                ('urlAPI', models.CharField(max_length=100, null=True)),
                ('frecuenciaMaxPosible', models.IntegerField(null=True)),
                ('fechaAltaProveedorInfoClimatica', models.DateTimeField()),
                ('fechaBajaProveedorInfoClimatica', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProveedorInformacionClimaticaFinca',
            fields=[
                ('OIDProveedorInformacionClimaticaFinca', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fechaAltaProveedorInfoClimaticaFinca', models.DateTimeField()),
                ('fechaBajaProveedorInfoClimaticaFinca', models.DateTimeField(null=True)),
                ('frecuencia', models.IntegerField(null=True)),
                ('finca', models.ForeignKey(db_column=b'OIDFinca', null=True, on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.Finca')),
                ('proveedorInformacionClimatica', models.ForeignKey(db_column=b'OIDProveedorInformacionClimatica', null=True, on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.ProveedorInformacionClimatica')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('OIDRol', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombreRol', models.CharField(max_length=30)),
                ('fechaAltaRol', models.DateTimeField()),
                ('fechaBajaRol', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RolUsuarioFinca',
            fields=[
                ('OIDRolUsuarioFinca', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fechaAltaRolUsuarioFinca', models.DateTimeField()),
                ('fechaBajaRolUsuarioFinca', models.DateTimeField(null=True)),
                ('rol', models.ForeignKey(db_column=b'OIDRol', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.Rol')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('OIDSector', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idSector', models.IntegerField(default=1, editable=False, unique=True)),
                ('numeroSector', models.IntegerField()),
                ('nombreSector', models.CharField(max_length=30)),
                ('descripcionSector', models.CharField(max_length=100)),
                ('superficie', models.FloatField()),
                ('finca', models.ForeignKey(db_column=b'OIDFinca', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sectorList', to='riegoInteligente.Finca')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('OIDSensor', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idSensor', models.IntegerField(default=1, editable=False, unique=True)),
                ('fechaAltaSensor', models.DateTimeField()),
                ('fechaBajaSensor', models.DateTimeField(null=True)),
                ('habilitado', models.BooleanField()),
                ('modelo', models.CharField(max_length=20)),
                ('finca', models.ForeignKey(db_column=b'OIDFinca', null=True, on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.Finca')),
            ],
        ),
        migrations.CreateModel(
            name='SesionUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_y_hora_ultimo_acceso', models.DateTimeField(null=True)),
                ('fecha_y_hora_fin', models.DateTimeField(null=True)),
                ('fecha_y_hora_inicio', models.DateTimeField(null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.Session')),
            ],
        ),
        migrations.CreateModel(
            name='SubtipoCultivo',
            fields=[
                ('OIDSubtipoCultivo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombreSubtipo', models.CharField(max_length=20)),
                ('habilitado', models.BooleanField()),
                ('descripcion', models.CharField(max_length=100)),
                ('fechaAltaSubtipoCultivo', models.DateTimeField()),
                ('fechaBajaSubtipoCultivo', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoConfiguracionRiego',
            fields=[
                ('OIDTipoConfiguracionRiego', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idTipoConfiguracion', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCultivo',
            fields=[
                ('OIDTipoCultivo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombreTipoCultivo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('habilitado', models.BooleanField()),
                ('fechaAltaTipoCultivo', models.DateTimeField()),
                ('fechaBajaTipoCultivo', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMecanismoRiego',
            fields=[
                ('OIDTipoMecanismoRiego', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombreMecanismo', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.CharField(max_length=200, null=True)),
                ('caudalEstandar', models.FloatField(null=True)),
                ('presionEstandar', models.FloatField(null=True)),
                ('eficiencia', models.FloatField(null=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('fechaAltaTipoMecanismoRiego', models.DateTimeField()),
                ('fechaBajaTipoMecanismoRiego', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMedicion',
            fields=[
                ('OIDTipoMedicion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idTipoMedicion', models.IntegerField(default=1, editable=False, unique=True)),
                ('nombreTipoMedicion', models.CharField(max_length=20)),
                ('unidadMedicion', models.CharField(max_length=20)),
                ('habilitado', models.BooleanField()),
                ('fechaAltaTipoMedicion', models.DateTimeField()),
                ('fechaBajaTipoMedicion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMedicionClimatica',
            fields=[
                ('OIDTipoMedicionClimatica', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idTipoMedicionClimatica', models.IntegerField(default=1, editable=False, unique=True)),
                ('nombreTipoMedicionClimatica', models.CharField(max_length=30, unique=True)),
                ('unidadMedicion', models.CharField(max_length=20, null=True)),
                ('habilitada', models.BooleanField()),
                ('fechaAltaTipoMedicionClimatica', models.DateTimeField()),
                ('fechaBajaTipoMedicionClimatica', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSesion',
            fields=[
                ('OIDTipoSesion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idTipo', models.IntegerField()),
                ('nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioFinca',
            fields=[
                ('OIDUsuarioFinca', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idUsuarioFinca', models.IntegerField(default=1, editable=False, unique=True)),
                ('fechaAltaUsuarioFinca', models.DateTimeField()),
                ('fechaBajaUsuarioFinca', models.DateTimeField(null=True)),
                ('configuracionEventoPersonalizadoList', models.ManyToManyField(null=True, to='riegoInteligente.ConfiguracionEventoPersonalizado')),
                ('finca', models.ForeignKey(db_column=b'OIDFinca', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.Finca')),
                ('usuario', models.ForeignKey(db_column=b'OIDUsuario', on_delete=django.db.models.deletion.CASCADE, related_name='usuarioFincaList', to='riegoInteligente.DatosUsuario')),
            ],
        ),
        migrations.CreateModel(
            name='CriterioRiegoPorHora',
            fields=[
                ('criterioriego_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='riegoInteligente.CriterioRiego')),
                ('hora', models.DateTimeField()),
                ('numeroDia', models.IntegerField()),
            ],
            bases=('riegoInteligente.criterioriego',),
        ),
        migrations.CreateModel(
            name='CriterioRiegoPorMedicion',
            fields=[
                ('criterioriego_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='riegoInteligente.CriterioRiego')),
                ('valor', models.FloatField()),
                ('tipo_medicion', models.ForeignKey(db_column=b'OIDTipoMedicion', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criterios_riego_medicion_list', to='riegoInteligente.TipoMedicion')),
            ],
            bases=('riegoInteligente.criterioriego',),
        ),
        migrations.CreateModel(
            name='CriterioRiegoVolumenAgua',
            fields=[
                ('criterioriego_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='riegoInteligente.CriterioRiego')),
                ('volumen', models.FloatField()),
            ],
            bases=('riegoInteligente.criterioriego',),
        ),
        migrations.CreateModel(
            name='MedicionEstadoExterno',
            fields=[
                ('medicionevento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='riegoInteligente.MedicionEvento')),
                ('tipoMedicion', models.ForeignKey(db_column=b'OIDTipoMedicionClimatica', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.TipoMedicionClimatica')),
            ],
            bases=('riegoInteligente.medicionevento',),
        ),
        migrations.CreateModel(
            name='MedicionFuenteInterna',
            fields=[
                ('medicionevento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='riegoInteligente.MedicionEvento')),
                ('tipoMedicion', models.ForeignKey(db_column=b'OIDTipoMedicion', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.TipoMedicion')),
            ],
            bases=('riegoInteligente.medicionevento',),
        ),
        migrations.AddField(
            model_name='subtipocultivo',
            name='tipo_cultivo',
            field=models.ForeignKey(db_column=b'OIDTipoCultivo', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.TipoCultivo'),
        ),
        migrations.AddField(
            model_name='sesionusuario',
            name='tipo_sesion',
            field=models.ForeignKey(db_column=b'OIDTipoSesion', null=True, on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.TipoSesion'),
        ),
        migrations.AddField(
            model_name='sesionusuario',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sensor',
            name='tipoMedicion',
            field=models.ForeignKey(db_column=b'OIDTipoMedicion', null=True, on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.TipoMedicion'),
        ),
        migrations.AddField(
            model_name='rolusuariofinca',
            name='usuarioFinca',
            field=models.ForeignKey(db_column=b'OIDUsuarioFinca', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rolUsuarioFincaList', to='riegoInteligente.UsuarioFinca'),
        ),
        migrations.AddField(
            model_name='proveedorinformacionclimatica',
            name='tipoMedicionClimatica',
            field=models.ManyToManyField(to='riegoInteligente.TipoMedicionClimatica'),
        ),
        migrations.AddField(
            model_name='medicioninformacionclimaticadetalle',
            name='tipo_medicion_climatica',
            field=models.ForeignKey(db_column=b'OIDTipoMedicionClimatica', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.TipoMedicionClimatica'),
        ),
        migrations.AddField(
            model_name='medicioninformacionclimaticacabecera',
            name='proveedor_informacion_climatica_externa',
            field=models.ForeignKey(db_column=b'OIDProveedorInformacionClimaticaFinca', on_delete=django.db.models.deletion.CASCADE, related_name='medicionInformacionClimaticaCabeceraList', to='riegoInteligente.ProveedorInformacionClimaticaFinca'),
        ),
        migrations.AddField(
            model_name='medicionevento',
            name='configuracionEventoPersonalizado',
            field=models.ForeignKey(db_column=b'OIDConfiguracionEventoPersonalizado', on_delete=django.db.models.deletion.CASCADE, related_name='medicionEventoList', to='riegoInteligente.ConfiguracionEventoPersonalizado'),
        ),
        migrations.AddField(
            model_name='mediciondetalle',
            name='tipoMedicion',
            field=models.ForeignKey(db_column=b'OIDTipoMedicion', null=True, on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.TipoMedicion'),
        ),
        migrations.AddField(
            model_name='mecanismoriegofincasector',
            name='sector',
            field=models.ForeignKey(db_column=b'OIDSector', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mecanismoRiegoFincaSector', to='riegoInteligente.Sector'),
        ),
        migrations.AddField(
            model_name='mecanismoriegofinca',
            name='tipoMecanismoRiego',
            field=models.ForeignKey(db_column=b'OIDTipoMecanismoRiego', null=True, on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.TipoMecanismoRiego'),
        ),
        migrations.AddField(
            model_name='historicomecanismoriegofincasector',
            name='mecanismo_riego_finca_sector',
            field=models.ForeignKey(db_column=b'OIDMecanismoRiegoFincaSector', on_delete=django.db.models.deletion.CASCADE, related_name='historicoMecanismoRiegoFincaSector', to='riegoInteligente.MecanismoRiegoFincaSector'),
        ),
        migrations.AddField(
            model_name='historicomecanismoriegofinca',
            name='mecanismo_riego_finca',
            field=models.ForeignKey(db_column=b'OIDMecanismoRiegoFinca', on_delete=django.db.models.deletion.CASCADE, related_name='historicoMecanismoRiegoFincaList', to='riegoInteligente.MecanismoRiegoFinca'),
        ),
        migrations.AddField(
            model_name='historicoestadosector',
            name='sector',
            field=models.ForeignKey(db_column=b'OIDSector', on_delete=django.db.models.deletion.CASCADE, related_name='historicoEstadoSectorList', to='riegoInteligente.Sector'),
        ),
        migrations.AddField(
            model_name='eventopersonalizado',
            name='sector',
            field=models.ForeignKey(db_column=b'OIDSector', null=True, on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.Sector'),
        ),
        migrations.AddField(
            model_name='ejecucionriego',
            name='estado_ejecucion_riego',
            field=models.ForeignKey(db_column=b'OIDEstadoEjecucionRiego', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.EstadoEjecucionRiego'),
        ),
        migrations.AddField(
            model_name='ejecucionriego',
            name='mecanismo_riego_finca_sector',
            field=models.ForeignKey(db_column=b'OIDMecanismoRiegoFincaSector', on_delete=django.db.models.deletion.CASCADE, related_name='ejecucionRiegoList', to='riegoInteligente.MecanismoRiegoFincaSector'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='sector',
            field=models.ForeignKey(db_column=b'OIDSector', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.Sector'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='subtipo_cultivo',
            field=models.ForeignKey(db_column=b'OIDSubtipoCultivo', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.SubtipoCultivo'),
        ),
        migrations.AddField(
            model_name='criterioriego',
            name='configuracionRiegoFinal',
            field=models.ForeignKey(db_column=b'OIDConfiguracionRiegoFinal', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criterioRiegoFinal', to='riegoInteligente.ConfiguracionRiego'),
        ),
        migrations.AddField(
            model_name='criterioriego',
            name='configuracionRiegoInicial',
            field=models.OneToOneField(db_column=b'OIDConfiguracionRiegoInicial', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criterioRiegoInicial', to='riegoInteligente.ConfiguracionRiego'),
        ),
        migrations.AddField(
            model_name='conjuntopermisos',
            name='rol',
            field=models.ForeignKey(db_column=b'OIDRol', on_delete=django.db.models.deletion.CASCADE, related_name='conjuntoPermisos', to='riegoInteligente.Rol'),
        ),
        migrations.AddField(
            model_name='configuracionriego',
            name='mecanismoRiegoFincaSector',
            field=models.ForeignKey(db_column=b'OIDMecanismoRiegoFincaSector', null=True, on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.MecanismoRiegoFincaSector'),
        ),
        migrations.AddField(
            model_name='configuracionriego',
            name='tipoConfiguracionRiego',
            field=models.ForeignKey(db_column=b'OIDTipoConfiguracionRiego', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.TipoConfiguracionRiego'),
        ),
        migrations.AddField(
            model_name='configuracioneventopersonalizado',
            name='sectorList',
            field=models.ManyToManyField(null=True, to='riegoInteligente.Sector'),
        ),
        migrations.AddField(
            model_name='componentesensorsector',
            name='sector',
            field=models.ForeignKey(db_column=b'OIDSector', null=True, on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.Sector'),
        ),
        migrations.AddField(
            model_name='componentesensor',
            name='finca',
            field=models.ForeignKey(db_column=b'OIDFinca', null=True, on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.Finca'),
        ),
        migrations.AddField(
            model_name='caracteristicasubtipo',
            name='subtipo_cultivo',
            field=models.ForeignKey(db_column=b'OIDSubtipoCultivo', on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicaSubtipoList', to='riegoInteligente.SubtipoCultivo'),
        ),
        migrations.AddField(
            model_name='asignacionsensorcomponente',
            name='componenteSensor',
            field=models.ForeignKey(db_column=b'OIDComponenteSensor', on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_list', to='riegoInteligente.ComponenteSensor'),
        ),
        migrations.AddField(
            model_name='asignacionsensorcomponente',
            name='sensor',
            field=models.ForeignKey(db_column=b'OIDSensor', on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_list', to='riegoInteligente.Sensor'),
        ),
    ]
