# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 20:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('riegoInteligente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finca',
            name='proveedor_informacion_climatica_finca',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario',
        ),
        migrations.AddField(
            model_name='proveedorinformacionclimaticafinca',
            name='finca',
            field=models.ForeignKey(db_column=b'OIDFinca', null=True, on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.Finca'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='criterioriego',
            name='configuracionRiegoFinal',
            field=models.ForeignKey(db_column=b'OIDConfiguracionRiegoFinal', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criterioRiegoFinal', to='riegoInteligente.ConfiguracionRiego'),
        ),
        migrations.AlterField(
            model_name='criterioriego',
            name='configuracionRiegoInicial',
            field=models.OneToOneField(db_column=b'OIDConfiguracionRiegoInicial', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criterioRiegoInicial', to='riegoInteligente.ConfiguracionRiego'),
        ),
        migrations.AlterField(
            model_name='estadomecanismoriegofincasector',
            name='nombreEstadoMecanismoRiegoFincaSector',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='finca',
            name='logoFinca',
            field=models.ImageField(null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='OIDEstadoUsuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.EstadoUsuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cuit',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='domicilio',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fechaNacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='imagenUsuario',
            field=models.ImageField(null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
