# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='idSector',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
