# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 23:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('riegoInteligente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConjuntoPermisos',
            fields=[
                ('OIDConjuntoPermisos', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('puedeAsignarComponenteSensor', models.BooleanField()),
                ('puedeAsignarCultivo', models.BooleanField()),
                ('puedeAsignarMecRiegoAFinca', models.BooleanField()),
                ('puedeAsignarMecRiegoASector', models.BooleanField()),
                ('puedeConfigurarObtencionInfoExterna', models.BooleanField()),
                ('puedeCrearComponenteSensor', models.BooleanField()),
                ('puedeCrearConfiguracionRiego', models.BooleanField()),
                ('puedeCrearSector', models.BooleanField()),
                ('puedeGenerarInformeCruzadoRiegoMedicion', models.BooleanField()),
                ('puedeGenerarInformeEstadoActualSectores', models.BooleanField()),
                ('puedeGenerarInformeEstadoHistoricoSectoresFinca', models.BooleanField()),
                ('puedeGenerarInformeEventoPersonalizado', models.BooleanField()),
                ('puedeGenerarInformeHeladasHistorico', models.BooleanField()),
                ('puedeGenerarInformeRiegoEnEjecucion', models.BooleanField()),
                ('puedeGenerarInformeRiegoPorSectoresHistorico', models.BooleanField()),
                ('puedeGestionarComponenteSensor', models.BooleanField()),
                ('puedeGestionarCultivoSector', models.BooleanField()),
                ('puedeGestionarEventoPersonalizado', models.BooleanField()),
                ('puedeGestionarFinca', models.BooleanField()),
                ('puedeGestionarSector', models.BooleanField()),
                ('puedeGestionarSensores', models.BooleanField()),
                ('puedeGestionarUsuariosFinca', models.BooleanField()),
                ('puedeIniciarODetenerRiegoManualmente', models.BooleanField()),
                ('puedeModificarConfiguracionRiego', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DatosUsuario',
            fields=[
                ('OIDDatosUsuario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cuit', models.CharField(max_length=15, null=True)),
                ('dni', models.IntegerField(null=True)),
                ('domicilio', models.CharField(max_length=50, null=True)),
                ('fechaNacimiento', models.DateTimeField(null=True)),
                ('imagenUsuario', models.ImageField(null=True, upload_to=b'')),
                ('reset_password', models.BooleanField(default=False)),
                ('codigoVerificacion', models.CharField(max_length=10, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RolUsuarioFinca',
            fields=[
                ('OIDRolUsuarioFinca', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fechaAltaRolUsuarioFinca', models.DateTimeField()),
                ('fechaBajaRolUsuarioFinca', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SesionUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_y_hora_ultimo_acceso', models.DateTimeField(null=True)),
                ('fecha_y_hora_fin', models.DateTimeField(null=True)),
                ('fecha_y_hora_inicio', models.DateTimeField(null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.Session')),
                ('tipo_sesion', models.ForeignKey(db_column=b'OIDTipoSesion', null=True, on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.TipoSesion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMecanismoRiego',
            fields=[
                ('OIDTipoMecanismoRiego', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombreMecanismo', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.CharField(max_length=200, null=True)),
                ('presionEstandar', models.FloatField(null=True)),
                ('eficiencia', models.FloatField(null=True)),
                ('fechaAltaTipoMecanismoRiego', models.DateTimeField()),
                ('fechaBajaTipoMecanismoRiego', models.DateTimeField(null=True)),
                ('habilitado', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contrasenia',
            name='OIDUsuario',
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='tipoSesion',
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='OIDEstadoUsuario',
        ),
        migrations.RenameField(
            model_name='estadomecanismoriegofinca',
            old_name='descripcionEstadoMecanismoRiegoFincaSector',
            new_name='descripcionEstadoMecanismoRiegoFinca',
        ),
        migrations.RenameField(
            model_name='estadomecanismoriegofinca',
            old_name='nombreEstadoMecanismoRiegoFincaSector',
            new_name='nombreEstadoMecanismoRiegoFinca',
        ),
        migrations.RenameField(
            model_name='historicoestadofinca',
            old_name='estado_finca',
            new_name='estadoFinca',
        ),
        migrations.RemoveField(
            model_name='finca',
            name='logoFinca',
        ),
        migrations.RemoveField(
            model_name='finca',
            name='proveedor_informacion_climatica_finca',
        ),
        migrations.RemoveField(
            model_name='mecanismoriegofinca',
            name='idFincaMecanismoRiego',
        ),
        migrations.AddField(
            model_name='historicomecanismoriegofinca',
            name='fechaFinEstadoMecanismoRiegoFinca',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='historicomecanismoriegofinca',
            name='fechaInicioEstadoMecanismoRiegoFinca',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='mecanismoriegofinca',
            name='idMecanismoRiegoFinca',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AddField(
            model_name='proveedorinformacionclimaticafinca',
            name='finca',
            field=models.ForeignKey(db_column=b'OIDFinca', null=True, on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.Finca'),
        ),
        migrations.AddField(
            model_name='proveedorinformacionclimaticafinca',
            name='proveedorInformacionClimatica',
            field=models.ForeignKey(db_column=b'OIDProveedorInformacionClimatica', null=True, on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.ProveedorInformacionClimatica'),
        ),
        migrations.AlterField(
            model_name='componentesensor',
            name='fechaAltaComponenteSensor',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='componentesensor',
            name='fechaBajaComponenteSensor',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='configuracioneventopersonalizado',
            name='fechaAltaConfiguracionEventoPersonalizado',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='configuracioneventopersonalizado',
            name='fechaBajaConfiguracionEventoPersonalizado',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='configuracioneventopersonalizado',
            name='fechaHoraCreacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='configuracionriego',
            name='fechaCreacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='configuracionriego',
            name='fechaFinalizacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='criterioriego',
            name='configuracionRiegoFinal',
            field=models.ForeignKey(db_column=b'OIDConfiguracionRiegoFinal', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criterioRiegoFinal', to='riegoInteligente.ConfiguracionRiego'),
        ),
        migrations.AlterField(
            model_name='criterioriego',
            name='configuracionRiegoInicial',
            field=models.OneToOneField(db_column=b'OIDConfiguracionRiegoInicial', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criterioRiegoInicial', to='riegoInteligente.ConfiguracionRiego'),
        ),
        migrations.AlterField(
            model_name='criterioriego',
            name='fechaCreacionCriterio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='criterioriegoporhora',
            name='hora',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='fechaEliminacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='fechaPlantacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ejecucionriego',
            name='fechaHoraFinalProgramada',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ejecucionriego',
            name='fechaHoraFinalizacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ejecucionriego',
            name='fechaHoraInicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ejecucionriego',
            name='fechaHoraInicioProgramada',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='estadofinca',
            name='nombreEstadoFinca',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='estadomecanismoriegofincasector',
            name='nombreEstadoMecanismoRiegoFincaSector',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='eventopersonalizado',
            name='fechaHora',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='finca',
            name='idFinca',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='historicocomponentesensorsector',
            name='fechaAltaComponenteSensorSector',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicocomponentesensorsector',
            name='fechaBajaComponenteSensorSecto',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicoestadoconfiguracionriego',
            name='fechaFinEstadoConfiguracionRiego',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicoestadoconfiguracionriego',
            name='fechaInicioEstadoConfiguracionRiego',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicoestadofinca',
            name='fechaFinEstadoFinca',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='historicoestadofinca',
            name='fechaInicioEstadoFinca',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicoestadofinca',
            name='finca',
            field=models.ForeignKey(db_column=b'OIDFinca', on_delete=django.db.models.deletion.CASCADE, related_name='historicoEstadoFincaList', to='riegoInteligente.Finca'),
        ),
        migrations.AlterField(
            model_name='historicoestadosector',
            name='fechaFinEstadoSector',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='historicoestadosector',
            name='fechaInicioEstadoSector',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicoestadousuario',
            name='fechaFinEstadoUsuario',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='historicoestadousuario',
            name='fechaInicioEstadoUsuario',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicoestadousuario',
            name='usuario',
            field=models.ForeignKey(db_column=b'OIDUsuario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historicoEstadoUsuarioList', to='riegoInteligente.DatosUsuario'),
        ),
        migrations.AlterField(
            model_name='historicomecanismoriegofinca',
            name='mecanismo_riego_finca',
            field=models.ForeignKey(db_column=b'OIDMecanismoRiegoFinca', on_delete=django.db.models.deletion.CASCADE, related_name='historicoMecanismoRiegoFincaList', to='riegoInteligente.MecanismoRiegoFinca'),
        ),
        migrations.AlterField(
            model_name='historicomecanismoriegofincasector',
            name='fechaFinEstadoMecanismoRiegoFincaSector',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicomecanismoriegofincasector',
            name='fechaInicioEstadoMecanismoRiegoFincaSector',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='mecanismoriegofinca',
            name='fechaInstalacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='medicioncabecera',
            name='fechaYHora',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='medicioninformacionclimaticacabecera',
            name='fechaHora',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='proveedorinformacionclimatica',
            name='fechaAltaProveedorInfoClimatica',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='proveedorinformacionclimatica',
            name='fechaBajaProveedorInfoClimatica',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='proveedorinformacionclimatica',
            name='frecuenciaMaxPosible',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='proveedorinformacionclimatica',
            name='urlAPI',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedorinformacionclimaticafinca',
            name='fechaAltaProveedorInfoClimaticaFinca',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='proveedorinformacionclimaticafinca',
            name='fechaBajaProveedorInfoClimaticaFinca',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='proveedorinformacionclimaticafinca',
            name='frecuencia',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='fechaAltaRol',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rol',
            name='fechaBajaRol',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombreRol',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='fechaAltaSensor',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='fechaBajaSensor',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subtipocultivo',
            name='fechaAltaSubtipoCultivo',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subtipocultivo',
            name='fechaBajaSubtipoCultivo',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tipocultivo',
            name='fechaAltaTipoCultivo',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tipocultivo',
            name='fechaBajaTipoCultivo',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tipomedicion',
            name='fechaAltaTipoMedicion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tipomedicion',
            name='fechaBajaTipoMedicion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tipomedicionclimatica',
            name='fechaAltaTipoMedicionClimatica',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tipomedicionclimatica',
            name='fechaBajaTipoMedicionClimatica',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='usuariofinca',
            name='fechaAltaUsuarioFinca',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='usuariofinca',
            name='fechaBajaUsuarioFinca',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usuariofinca',
            name='usuario',
            field=models.ForeignKey(db_column=b'OIDUsuario', on_delete=django.db.models.deletion.CASCADE, related_name='usuarioFincaList', to='riegoInteligente.DatosUsuario'),
        ),
        migrations.DeleteModel(
            name='Contrasenia',
        ),
        migrations.DeleteModel(
            name='Sesion',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='rolusuariofinca',
            name='rol',
            field=models.ForeignKey(db_column=b'OIDRol', on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.Rol'),
        ),
        migrations.AddField(
            model_name='rolusuariofinca',
            name='usuarioFinca',
            field=models.ForeignKey(db_column=b'OIDUsuarioFinca', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rolUsuarioFincaList', to='riegoInteligente.UsuarioFinca'),
        ),
        migrations.AddField(
            model_name='conjuntopermisos',
            name='rol',
            field=models.ForeignKey(db_column=b'OIDRol', on_delete=django.db.models.deletion.CASCADE, related_name='conjuntoPermisos', to='riegoInteligente.Rol'),
        ),
        migrations.AddField(
            model_name='mecanismoriegofinca',
            name='tipoMecanismoRiego',
            field=models.ForeignKey(db_column=b'OIDTipoMecanismoRiego', null=True, on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.TipoMecanismoRiego'),
        ),
    ]
