# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediciondetalle',
            name='medicionCabecera',
            field=models.ForeignKey(db_column=b'OIDMedicionCabecera', on_delete=django.db.models.deletion.CASCADE, related_name='medicionDetalleList', to='riegoInteligente.MedicionCabecera'),
        ),
    ]
