# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0002_auto_20171012_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='fechaBajaRol',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
