# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0002_auto_20170902_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoestadousuario',
            name='fechaInicioEstadoUsuario',
            field=models.DateField(null=True),
        ),
    ]
