# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0002_sector_idsector'),
    ]

    operations = [
        migrations.AddField(
            model_name='mecanismoriegofincasector',
            name='mecanismo_riego_finca',
            field=models.ForeignKey(db_column=b'OIDMecanismoRiegoFinca', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mecanismoRiegoSectorList', to='riegoInteligente.MecanismoRiegoFinca'),
        ),
    ]
