# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0003_auto_20171021_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterioriego',
            name='configuracionRiegoInicial',
            field=models.ForeignKey(db_column=b'OIDConfiguracionRiegoInicial', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criterioRiegoInicial', to='riegoInteligente.ConfiguracionRiego'),
        ),
    ]
