# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0003_auto_20170917_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariofinca',
            name='idUsuarioFinca',
        ),
    ]
