# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0003_auto_20171016_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtipocultivo',
            name='fechaBajaSubtipoCultivo',
        ),
        migrations.AddField(
            model_name='subtipocultivo',
            name='fechaBajaSubTipoCultivo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proveedorinformacionclimatica',
            name='fechaBajaProveedorInfoClimatica',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipocultivo',
            name='fechaBajaTipoCultivo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipomecanismoriego',
            name='fechaBajaTipoMecanismoRiego',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipomedicion',
            name='fechaBajaTipoMedicion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipomedicionclimatica',
            name='fechaBajaTipoMedicionClimatica',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
