# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0003_mecanismoriegofincasector_mecanismo_riego_finca'),
    ]

    operations = [
        migrations.AddField(
            model_name='mecanismoriegofincasector',
            name='sector',
            field=models.ForeignKey(db_column=b'OIDSector', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sector', to='riegoInteligente.Sector'),
        ),
    ]
