# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0004_auto_20171019_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoconfiguracionriego',
            name='idTipoConfiguracion',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
