# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0004_mecanismoriegofincasector_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipomecanismoriego',
            name='caudalEstandar',
            field=models.FloatField(null=True),
        ),
    ]
