# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0004_remove_usuariofinca_idusuariofinca'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariofinca',
            name='idUsuarioFinca',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
