# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0005_auto_20171027_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivo',
            name='cantidad_plantas_hectarea',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='configuracioneventopersonalizado',
            name='fechaBajaConfiguracionEventoPersonalizado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
