# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0005_usuariofinca_idusuariofinca'),
    ]

    operations = [
        migrations.AddField(
            model_name='finca',
            name='logoFinca',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
