# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0005_auto_20170903_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoestadousuario',
            name='fechaFinEstadoUsuario',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='historicoestadousuario',
            name='fechaInicioEstadoUsuario',
            field=models.DateField(),
        ),
    ]
