# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0005_tipomecanismoriego_caudalestandar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mecanismoriegofincasector',
            name='OIDMecanismoRiegoFincaSector',
            field=models.UUIDField(default=uuid.UUID('93188413-7852-4277-953e-27ee1289fcfc'), editable=False, primary_key=True, serialize=False),
        ),
    ]
