# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0006_finca_logofinca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metodoproveedorinformacionclimatica',
            name='proveedor_informacion_climatica',
        ),
        migrations.RemoveField(
            model_name='parametro',
            name='metodo_proveedor_informacion_climatica',
        ),
        migrations.RemoveField(
            model_name='tipomedicionclimatica',
            name='metodo_proveedor_informacion_climatica',
        ),
        migrations.AlterField(
            model_name='componentesensor',
            name='fechaBajaComponenteSensor',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='configuracioneventopersonalizado',
            name='fechaBajaConfiguracionEventoPersonalizado',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='fechaEliminacion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='historicocomponentesensorsector',
            name='fechaBajaComponenteSensorSecto',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='medicioninformacionclimaticacabecera',
            name='OIDMedicionInformacionClimaticaCabecera',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medicioninformacionclimaticadetalle',
            name='OIDMedicionInformacionClimaticaDetalle',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proveedorinformacionclimatica',
            name='OIDProveedorInformacionClimatica',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='fechaBajaSensor',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='subtipocultivo',
            name='fechaBajaSubtipoCultivo',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tipocultivo',
            name='fechaBajaTipoCultivo',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tipomedicion',
            name='fechaBajaTipoMedicion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tipomedicionclimatica',
            name='OIDTipoMedicionClimatica',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipomedicionclimatica',
            name='fechaBajaTipoMedicionClimatica',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='MetodoProveedorInformacionClimatica',
        ),
        migrations.DeleteModel(
            name='Parametro',
        ),
    ]
