# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0006_auto_20170922_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicomecanismoriegofincasector',
            name='fechaFinEstadoMecanismoRiegoFincaSector',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mecanismoriegofincasector',
            name='OIDMecanismoRiegoFincaSector',
            field=models.UUIDField(default=uuid.UUID('33320aee-511d-4c89-a7c3-2308857a1966'), editable=False, primary_key=True, serialize=False),
        ),
    ]
