# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0006_auto_20171030_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristicasubtipo',
            name='atributo',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='caracteristicasubtipo',
            name='valor',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='configuracioneventopersonalizado',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='estadocomponentesensor',
            name='nombreEstado',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='estadocomponentesensorsector',
            name='nombreEstadoComponenteSensorSector',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='estadoconfiguracionriego',
            name='nombreEstadoConfiguracionRiego',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='estadoejecucionriego',
            name='nombreEstadoEjecucionRiego',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='estadomecanismoriegofinca',
            name='nombreEstadoMecanismoRiegoFinca',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='estadomecanismoriegofincasector',
            name='nombreEstadoMecanismoRiegoFincaSector',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='estadosector',
            name='nombreEstadoSector',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='finca',
            name='ubicacion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='modelo',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='subtipocultivo',
            name='nombreSubtipo',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tipoconfiguracionriego',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='tipocultivo',
            name='nombreTipoCultivo',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tipomecanismoriego',
            name='descripcion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tipomedicion',
            name='nombreTipoMedicion',
            field=models.CharField(max_length=30),
        ),
    ]
