# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0007_auto_20170904_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='horaUltimoAcceso',
            field=models.DateField(null=True),
        ),
    ]
