# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0007_auto_20170918_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='finca',
            field=models.ForeignKey(db_column=b'OIDFinca', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sectorList', to='riegoInteligente.Finca'),
        ),
        migrations.AlterField(
            model_name='historicoestadosector',
            name='sector',
            field=models.ForeignKey(db_column=b'OIDSector', on_delete=django.db.models.deletion.CASCADE, related_name='historicoEstadoSectorList', to='riegoInteligente.Sector'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='nombreSector',
            field=models.CharField(max_length=30),
        ),
    ]
