# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0008_auto_20170922_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mecanismoriegofincasector',
            name='OIDMecanismoRiegoFincaSector',
            field=models.UUIDField(default=uuid.UUID('8a55e4ad-c849-4668-a27b-66a02b32e769'), editable=False, primary_key=True, serialize=False),
        ),
    ]
