# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0009_auto_20170922_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtipocultivo',
            name='idSubtipo',
        ),
        migrations.RemoveField(
            model_name='tipocultivo',
            name='idTipo',
        ),
        migrations.AlterField(
            model_name='mecanismoriegofincasector',
            name='OIDMecanismoRiegoFincaSector',
            field=models.UUIDField(default=uuid.UUID('68c01871-412d-4b61-8f34-491f5b6ddcb4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
