# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0009_auto_20170904_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedorinformacionclimatica',
            name='frecuenciaMaxPosible',
            field=models.IntegerField(null=True),
        ),
    ]
