# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0010_auto_20170904_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedorinformacionclimatica',
            name='fechaBajaProveedorInfoClimatica',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='proveedorinformacionclimatica',
            name='urlAPI',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
