# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0010_auto_20170923_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='mecanismoriegofincasector',
            name='idMecanismoRiegoFincaSector',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='mecanismoriegofincasector',
            name='OIDMecanismoRiegoFincaSector',
            field=models.UUIDField(default=uuid.UUID('04c6b037-ea7d-4af3-8f26-dfc49fe06c13'), editable=False, primary_key=True, serialize=False),
        ),
    ]
