# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0011_auto_20170904_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finca',
            name='idFinca',
        ),
    ]
