# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0011_auto_20170923_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivo',
            name='idCultivo',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='mecanismoriegofincasector',
            name='OIDMecanismoRiegoFincaSector',
            field=models.UUIDField(default=uuid.UUID('3c9af66f-9612-4823-ad55-13f704c0e422'), editable=False, primary_key=True, serialize=False),
        ),
    ]
