# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 00:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0012_remove_finca_idfinca'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedorinformacionclimaticafinca',
            name='proveedorInformacionClimatica',
            field=models.ForeignKey(db_column=b'OIDProveedorInformacionClimatica', null=True, on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.ProveedorInformacionClimatica'),
        ),
    ]
