# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0012_auto_20170923_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mecanismoriegofincasector',
            name='OIDMecanismoRiegoFincaSector',
            field=models.UUIDField(default=uuid.UUID('004bef35-0bc7-4cdf-af4d-590af4066151'), editable=False, primary_key=True, serialize=False),
        ),
    ]
