# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0013_auto_20170923_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mecanismoriegofincasector',
            name='OIDMecanismoRiegoFincaSector',
            field=models.UUIDField(default=uuid.UUID('08448e48-d702-482b-997f-cf6538be6eac'), editable=False, primary_key=True, serialize=False),
        ),
    ]
