# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0014_auto_20170904_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='fechaBajaRol',
            field=models.DateField(null=True),
        ),
    ]
