# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0015_auto_20170905_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadofinca',
            name='nombreEstadoFinca',
            field=models.CharField(max_length=50),
        ),
    ]
