# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0016_auto_20170924_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='componente_sensor',
            new_name='ComponenteSensor',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='sensorTipoInterna',
            new_name='tipoMedicion',
        ),
        migrations.AddField(
            model_name='sensor',
            name='finca',
            field=models.ForeignKey(db_column=b'OIDFinca', null=True, on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.Finca'),
        ),
        migrations.AlterField(
            model_name='mecanismoriegofincasector',
            name='OIDMecanismoRiegoFincaSector',
            field=models.UUIDField(default=uuid.UUID('f83a7110-9457-45b9-a171-b1d90d29eb6d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
