# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0017_auto_20170905_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoestadofinca',
            name='fechaFinEstadoFinca',
            field=models.DateField(null=True),
        ),
    ]
