# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0017_auto_20170924_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mecanismoriegofincasector',
            name='OIDMecanismoRiegoFincaSector',
            field=models.UUIDField(default=uuid.UUID('a6d5f652-ef7c-4c51-94ba-fd9f7a752cbf'), editable=False, primary_key=True, serialize=False),
        ),
    ]
