# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0018_auto_20170905_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariofinca',
            name='fechaBajaUsuarioFinca',
            field=models.DateField(null=True),
        ),
    ]
