# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0018_auto_20170924_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mecanismoriegofincasector',
            name='OIDMecanismoRiegoFincaSector',
            field=models.UUIDField(default=uuid.UUID('1f936310-406c-4fcf-b196-47e040252a32'), editable=False, primary_key=True, serialize=False),
        ),
    ]
