# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0019_auto_20170924_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mecanismoriegofincasector',
            old_name='mecanismo_riego_finca',
            new_name='mecanismoRiegoFinca',
        ),
        migrations.AlterField(
            model_name='mecanismoriegofincasector',
            name='OIDMecanismoRiegoFincaSector',
            field=models.UUIDField(default=uuid.UUID('a20ae223-b7a8-47a7-925c-6a3ca907b8b3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
