# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0019_auto_20170905_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedorinformacionclimaticafinca',
            name='fechaBajaProveedorInfoClimaticaFinca',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='proveedorinformacionclimaticafinca',
            name='frecuencia',
            field=models.IntegerField(null=True),
        ),
    ]
