# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0024_auto_20170907_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariofinca',
            name='usuario',
            field=models.ForeignKey(db_column=b'OIDUsuario', on_delete=django.db.models.deletion.CASCADE, related_name='usuarioFincaList', to='riegoInteligente.Usuario'),
        ),
    ]
