# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0026_auto_20170910_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolusuariofinca',
            old_name='fechaAltaUsuarioFinca',
            new_name='fechaAltaRolUsuarioFinca',
        ),
        migrations.RenameField(
            model_name='rolusuariofinca',
            old_name='fechaBajaUsuarioFinca',
            new_name='fechaBajaRolUsuarioFinca',
        ),
    ]
