# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0027_auto_20170910_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='fechaYHoraInicio',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='tipoSesion',
            field=models.ForeignKey(db_column=b'OIDTipoSesion', null=True, on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.TipoSesion'),
        ),
    ]
