# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0028_auto_20170911_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionCustom',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='session key')),
                ('session_data', models.TextField(verbose_name='session data')),
                ('expire_date', models.DateTimeField(db_index=True, verbose_name='expire date')),
                ('user_id', models.IntegerField(db_index=True, null=True)),
            ],
        ),
    ]
