# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 00:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0028_auto_20170911_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mecanismoriegofinca',
            old_name='idFincaMecanismoRiego',
            new_name='idMecanismoRiegoFinca',
        ),
        migrations.AddField(
            model_name='mecanismoriegofinca',
            name='tipoMecanismoRiego',
            field=models.ForeignKey(db_column=b'OIDTipoMecanismoRiego', null=True, on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.TipoMecanismoRiego'),
        ),
        migrations.AddField(
            model_name='tipomecanismoriego',
            name='descripcion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tipomecanismoriego',
            name='eficiencia',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tipomecanismoriego',
            name='fechaAltaTipoMecanismoRiego',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tipomecanismoriego',
            name='fechaBajaTipoMecanismoRiego',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tipomecanismoriego',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipomecanismoriego',
            name='nombreMecanismo',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tipomecanismoriego',
            name='presionEstandar',
            field=models.FloatField(null=True),
        ),
    ]
