# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0029_auto_20170911_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipomecanismoriego',
            name='fechaAltaTipoMecanismoRiego',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tipomecanismoriego',
            name='nombreMecanismo',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
