# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0030_auto_20170911_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicomecanismoriegofinca',
            name='mecanismo_riego_finca',
            field=models.ForeignKey(db_column=b'OIDMecanismoRiegoFinca', on_delete=django.db.models.deletion.CASCADE, related_name='historicoMecanismoRiegoFincaList', to='riegoInteligente.MecanismoRiegoFinca'),
        ),
        migrations.AlterField(
            model_name='mecanismoriegofinca',
            name='idMecanismoRiegoFinca',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
