# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0031_auto_20170914_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finca',
            name='idFinca',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
