# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 21:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('riegoInteligente', '0032_auto_20170914_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosUsuario',
            fields=[
                ('OIDUsuario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('codigoVerificacion', models.CharField(max_length=10, null=True)),
                ('apellido', models.CharField(max_length=30, null=True)),
                ('cuit', models.CharField(max_length=15, null=True)),
                ('dni', models.IntegerField(null=True)),
                ('domicilio', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('fechaNacimiento', models.DateTimeField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
        migrations.RemoveField(
            model_name='finca',
            name='logoFinca',
        ),
        migrations.AlterField(
            model_name='contrasenia',
            name='OIDUsuario',
            field=models.ForeignKey(db_column=b'OIDUsuario', on_delete=django.db.models.deletion.CASCADE, related_name='contrasenia', to='riegoInteligente.DatosUsuario'),
        ),
        migrations.AlterField(
            model_name='historicoestadousuario',
            name='usuario',
            field=models.ForeignKey(db_column=b'OIDUsuario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historicoEstadoUsuarioList', to='riegoInteligente.DatosUsuario'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='usuario',
            field=models.ForeignKey(db_column=b'OIDUsuario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sesionList', to='riegoInteligente.DatosUsuario'),
        ),
        migrations.AlterField(
            model_name='usuariofinca',
            name='usuario',
            field=models.ForeignKey(db_column=b'OIDUsuario', on_delete=django.db.models.deletion.CASCADE, related_name='usuarioFincaList', to='riegoInteligente.DatosUsuario'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
