# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0032_auto_20170912_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosusuario',
            name='reset_password',
            field=models.BooleanField(default=False),
        ),
    ]
