# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 04:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0033_datosusuario_reset_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='fechaYHoraInicio',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 14, 1, 23, 48, 92000), editable=False),
        ),
    ]
