# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0033_auto_20170916_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datosusuario',
            old_name='OIDUsuario',
            new_name='OIDDatosUsuario',
        ),
        migrations.AlterField(
            model_name='contrasenia',
            name='OIDUsuario',
            field=models.ForeignKey(db_column=b'OIDDatosUsuario', on_delete=django.db.models.deletion.CASCADE, related_name='contrasenia', to='riegoInteligente.DatosUsuario'),
        ),
        migrations.AlterField(
            model_name='historicoestadousuario',
            name='usuario',
            field=models.ForeignKey(db_column=b'OIDDatosUsuario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historicoEstadoUsuarioList', to='riegoInteligente.DatosUsuario'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='usuario',
            field=models.ForeignKey(db_column=b'OIDDatosUsuario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sesionList', to='riegoInteligente.DatosUsuario'),
        ),
        migrations.AlterField(
            model_name='usuariofinca',
            name='usuario',
            field=models.ForeignKey(db_column=b'OIDDatosUsuario', on_delete=django.db.models.deletion.CASCADE, related_name='usuarioFincaList', to='riegoInteligente.DatosUsuario'),
        ),
    ]
