# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0034_auto_20170914_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='fechaYHoraInicio',
            field=models.DateTimeField(null=True),
        ),
    ]
