# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 14:02
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('riegoInteligente', '0036_auto_20170914_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_y_hora_inicio', models.DateTimeField(default=datetime.datetime(2017, 9, 16, 11, 2, 43, 845000), editable=False)),
                ('fecha_y_hora_ultimo_acceso', models.DateTimeField(null=True)),
                ('fecha_y_hora_fin', models.DateTimeField(null=True)),
                ('session', models.ForeignKey(on_delete=models.SET(b'deleted_session'), to='sessions.Session')),
                ('tipo_sesion', models.ForeignKey(db_column=b'OIDTipoSesion', null=True, on_delete=django.db.models.deletion.CASCADE, to='riegoInteligente.TipoSesion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='tipoSesion',
        ),
        migrations.DeleteModel(
            name='Sesion',
        ),
    ]
