# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riegoInteligente', '0037_auto_20170916_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesionusuario',
            name='fecha_y_hora_inicio',
            field=models.DateTimeField(null=True),
        ),
    ]
