# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracionriego',
            old_name='tipo_configuracion_riego',
            new_name='tipoConfiguracionRiego',
        ),
        migrations.AddField(
            model_name='configuracionriego',
            name='mecanismoRiegoFincaSector',
            field=models.ForeignKey(db_column=b'OIDMecanismoRiegoFincaSector', null=True, on_delete=django.db.models.deletion.CASCADE, to='riego.MecanismoRiegoFincaSector'),
        ),
    ]
