# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0002_auto_20170820_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterioriego',
            name='configuracionRiegoFinal',
            field=models.ForeignKey(db_column=b'OIDConfiguracionRiegoFinal', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criterioRiegoFinal', to='riego.ConfiguracionRiego'),
        ),
        migrations.AlterField(
            model_name='criterioriego',
            name='configuracionRiegoInicial',
            field=models.OneToOneField(db_column=b'OIDconfiguracionRiegoInicial', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criterioRiegoInicial', to='riego.ConfiguracionRiego'),
        ),
        migrations.AlterField(
            model_name='estadomecanismoriegofincasector',
            name='nombreEstadoMecanismoRiegoFincaSector',
            field=models.CharField(max_length=20),
        ),
    ]
