# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0003_auto_20170821_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterioriego',
            name='configuracionRiegoFinal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criterioRiegoFinal', to='riego.ConfiguracionRiego'),
        ),
        migrations.AlterField(
            model_name='criterioriego',
            name='configuracionRiegoInicial',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criterioRiegoInicial', to='riego.ConfiguracionRiego'),
        ),
    ]
