# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0004_auto_20170821_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterioriego',
            name='configuracionRiegoFinal',
            field=models.ForeignKey(db_column=b'OIDConfiguracionRiegoFinal', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criterioRiegoFinal', to='riego.ConfiguracionRiego'),
        ),
        migrations.AlterField(
            model_name='criterioriego',
            name='configuracionRiegoInicial',
            field=models.OneToOneField(db_column=b'OIDConfiguracionRiegoInicial', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criterioRiegoInicial', to='riego.ConfiguracionRiego'),
        ),
    ]
