# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0005_auto_20170821_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finca',
            name='logoFinca',
            field=models.ImageField(null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='finca',
            name='proveedor_informacion_climatica_finca',
            field=models.ForeignKey(db_column=b'OIDProveedorInformacionClimaticaFinca', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finca', to='riego.ProveedorInformacionClimaticaFinca'),
        ),
    ]
