# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 23:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0006_auto_20170822_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finca',
            name='proveedor_informacion_climatica_finca',
        ),
        migrations.AddField(
            model_name='proveedorinformacionclimaticafinca',
            name='finca',
            field=models.ForeignKey(db_column=b'OIDFinca', null=True, on_delete=django.db.models.deletion.CASCADE, to='riego.Finca'),
        ),
    ]
