# source 'https://github.com/CocoaPods/Old-Specs.git'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Smart Farming App' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Smart Farming App

  pod 'AFNetworking', '~>3.0'
  pod 'CCTextFieldEffects'
  pod 'Masonry'

  target 'Smart Farming AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Smart Farming AppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
